config/routes.rb
SocialCookbook2::Application.routes.draw do
  resources :recipes

  get "home/index"

  resources :recipes do
	resources :ingredients
  end
  

  root :to => 'recipes#index'

end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  belongs_to :recipe
  attr_accessible :description, :measure, :unit
  
  validates :unit,  :presence => true, :length => { :minimum => 1 }
  validates :measure, :presence => true, :length => { :minimum => 3 }
  validates :description, :presence => true, :length => { :minimum => 3 }
  
  MEASURE = ['dash(s)','cup(s)','pint(s)','T(s)','tsp(s)','can(s)','box(s)','container(s)','gallon(s)','quart(s)','oz(s)','slice(s)','stick(s)']
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  attr_accessible :author, :category, :image, :instructions, :name
  
  validates :name,  :presence => true, :length => { :minimum => 3 }
  validates :author, :presence => true, :length => { :minimum => 3 }
  validates :category, :presence => true, :length => { :minimum => 3 }
  
  has_many :ingredients, :dependent => :destroy
  
  CATEGORIES = ['Appetizers', 'Beverages', 'Breads', 'Dessert',  'Main Dish', 'Salad', 'Side Dish', 'Soup', 'Vegetables']
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
	def create
		@recipe = Recipe.find(params[:recipe_id])
		@ingredient = @recipe.ingredients.create(params[:ingredient])
		redirect_to recipe_path(@recipe)
    end
	
	def destroy
		@recipe = Recipe.find(params[:recipe_id])
		@ingredient = @recipe.ingredients.find(params[:id])
		@ingredient.destroy
		redirect_to recipe_path(@recipe)
    end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  # GET /recipes
  # GET /recipes.json
  def index
    @recipes = Recipe.find(:all, :order => "updated_at desc")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @recipes }
    end
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
    @recipe = Recipe.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @recipe }
    end
  end

  # GET /recipes/new
  # GET /recipes/new.json
  def new
    @recipe = Recipe.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @recipe }
    end
  end

  # GET /recipes/1/edit
  def edit
    @recipe = Recipe.find(params[:id])
  end

  # POST /recipes
  # POST /recipes.json
  def create
    @recipe = Recipe.new(params[:recipe])

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
        format.json { render json: @recipe, status: :created, location: @recipe }
      else
        format.html { render action: "new" }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # PUT /recipes/1
  # PUT /recipes/1.json
  def update
    @recipe = Recipe.find(params[:id])

    respond_to do |format|
      if @recipe.update_attributes(params[:recipe])
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy

    respond_to do |format|
      format.html { redirect_to recipes_url }
      format.json { head :no_content }	 
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/home/index.html.erb
<h1>Keep going...</h1>
<%= link_to "Go to the Social Cookbook", recipes_path %>

app/views/ingredients/_form.html.erb

	<%= form_for([@recipe, @recipe.ingredients.build]) do |f| %>
	  <% if @recipe.errors.any? %>
		<div id="error_explanation">
		  <h2><%= pluralize(@recipe.errors.count, "error") %> prohibited this ingredient from being saved:</h2>

		  <ul>
		  <% @recipe.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
		  <% end %>
		  </ul>
		</div>
	  <% end %>
   <div class="row">
    <div class="span4 well">
	  <div class="field">
		<%= f.label 'Amount' %>
		<%= f.text_field :unit %>
	  </div>
	  <div class="field">
		<%= f.label :measure %>
		<%= f.collection_select :measure, Ingredient::MEASURE, :to_s, :to_s, :include_blank => false %>  
	  </div>
	  <div class="field">
		<%= f.label :description %>
		<%= f.text_field :description %>
	  </div>	  
	<%= f.submit "Add Ingredient", :class => 'btn btn-primary' %>
	  
	</div>
	</div>
	<% end %>

app/views/ingredients/_ingredient.html.erb
<%= ingredient.unit %> <%= ingredient.measure %> <%= ingredient.description %> <%= link_to 'Remove', [ingredient.recipe, ingredient], :confirm => 'Are you sure?', :method => :delete %></br> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SocialCookBook</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body data-spy="scroll" data-target=".subnav" data-offset="50">

<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
	<div class="container">
	  <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
		<span class="icon-bar"></span>
		<span class="icon-bar"></span>
		<span class="icon-bar"></span>
	  </a>	  
	  <%= link_to('the Social Cookbook', recipes_path, :class => 'brand') %>	
	  <div class="nav-collapse">
		<!-- here -->
	  </div>
	</div>
  </div>
</div>
		
<div class="container">
	<div class="marketing">
		<div class="content">			
			<div class="row">								
			    <div class="span12 columns">
					<%= yield %>
				</div>
			</div>
		</div>
	</div>
</div>
</body>
</html>

app/views/recipes/_form.html.erb
<%= form_for(@recipe) do |f| %>
  <% if @recipe.errors.any? %>
    <div id="error_explanation">
      <!-- <h2><%= pluralize(@recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2> -->
	  <div class="alert alert-error">
	  <ul>
      <% @recipe.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
	  </div>
    </div>
  <% end %>
<div class="row">
    <div class="span4 well">
	<p>Name your recipe</p>
    <%= f.text_field :name %>
	<p>Author</p>
    <%= f.text_field :author %> 
	<p>Select a category</p>
    <%= f.collection_select :category, Recipe::CATEGORIES, :to_s, :to_s, :include_blank => false %>  
	<p>Define some basic instructions</p>
    <%= f.text_area :instructions, :size => "40x15" %>	
	<br/><%= render @recipe.ingredients %><br/>	
    <!-- <%= f.text_field :image %>-->
    <%= f.submit "Save and continue", :class => 'btn btn-primary' %> <%= link_to('Cancel', recipes_path, :class => 'btn') %> 
  </div>
</div>
<% end %>

app/views/recipes/edit.html.erb
<div class="page-header">
	<h1>Edit recipe</h1>
</div>

<%= render 'form' %>

<%= link_to('Add more ingredients', @recipe, :class => 'btn') %> <%= link_to('Go back to dashboard', recipes_path, :class => 'btn') %> 

app/views/recipes/index.html.erb
<p><%= link_to('Add a recipe', new_recipe_path, :class => 'btn btn-success btn-large')  %></p>

 <div class="row">
    <div class="span8">
		<table class="table table-striped">
			<tbody>
				<% @recipes.each do |recipe| %>
				  <tr>
					<!--<td>
						<img src="<%= recipe.image %>" alt="<%= recipe.name %>" width=30 heigh=30 />
					</td>-->
					<td>
						<h3><%= recipe.name %></h3>
						<i><%= recipe.author %> | <%= recipe.category %></i>
						<p><small><%= recipe.instructions %></small></br>		
						<h5>
						<ul>
							<% recipe.ingredients.each do |ingredient| %>
								<li><%= ingredient.unit %> <%= ingredient.measure %> <%= ingredient.description %></li>
							<% end %>
						</ul>
						</h5>
						<%= link_to('Show', recipe, :class => 'btn btn-mini') %> <%= link_to('Edit', edit_recipe_path(recipe), :class => 'btn btn-mini') %> <%= link_to('Remove', recipe, confirm: 'Are you sure?', method: :delete, :class => 'btn btn-mini') %></p>				
					</td>			
				  </tr>
				<% end %>
			</tbody>
		</table>
	</div>
<div>

<br />

app/views/recipes/new.html.erb
<div class="page-header">
	<h1>Create a new recipe</h1>
</div>

<%= render 'form' %>

app/views/recipes/show.html.erb
<% if notice %>
	<div class="alert alert-success"><%= notice %></div>
<% end %>
<div class="page-header">
	<h1><%= @recipe.name %> <small><%= @recipe.author %>, <%= @recipe.category %></small></h1>
</div>
 
<h3>Instructions <small><%= link_to('Edit', edit_recipe_path(@recipe)) %></small></h3>
<p><%= @recipe.instructions %></p>

<h3>Ingredients</h3>
<%= render @recipe.ingredients %>
</br>
<h3>Add Ingredients:</h3>
<%= render "ingredients/form" %>

<p class="download-info">	  
	  <%= link_to('Save and finish', recipes_path, :class => 'btn btn-primary') %> 	  
	  <%= link_to('Delete recipe', @recipe, confirm: 'Are you sure?', method: :delete, :class => 'btn') %>	 	
	  <%= link_to('Go to dashboard', recipes_path, :class => 'btn') %>
</p>